// Copyright 2017-2026 @polkadot/api-contract authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/api-contract', path: 'auto', type: 'auto', version: '16.5.6-1-x' };
