// Copyright 2017-2022 @polkadot/types-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/types-augment', version: '7.1.2-4' };
