// Copyright 2017-2026 @polkadot/types-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/types-augment', path: 'auto', type: 'auto', version: '16.5.6-0-x' };
