// Copyright 2017-2021 @polkadot/types-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/types-augment', version: '6.12.2-26' };
