exclude_patterns:
- "**/*.spec.js"
- "**/*.spec.ts"
- "**/*.test.js"
- "**/*.test.ts"
- "docs/**/*.js"
- "packages/api/src/types/augment/"
- "packages/types/src/interfaces/"
- "packages/types/src/scripts/"
