exclude_patterns:
- "**/*.spec.js"
- "**/*.spec.ts"
- "**/*.test.js"
- "**/*.test.ts"
- "docs/**/*.js"
- "packages/types/src/interfaces/"
- "packages/types/src/scripts/"
checks:
  return-statements:
    enabled: true
    config:
      threshold: 5
