checks:
  argument-count:
    config:
      threshold: 5
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30

exclude_patterns:
- "**/*.spec.js"
- "**/*.spec.ts"
- "**/*.test.js"
- "**/*.test.ts"
- "docs/**/*.js"
- "docs/**/*.ts"
- "packages/api-augment/"
- "packages/rpc-augment/"
- "packages/typegen/scripts"
- "packages/typegen/src"
- "packages/types/src/interfaces/"
- "packages/types/src/augment/"
