// Copyright 2017-2021 @polkadot/types-augment-lookup authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/types-augment-lookup', version: '7.0.3-1' };
