// Copyright 2017-2025 @polkadot/types-support authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/types-support', path: 'auto', type: 'auto', version: '15.10.1' };
