// Copyright 2017-2024 @polkadot/api-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/api-augment', path: 'auto', type: 'auto', version: '11.2.2-3-x' };
