// Copyright 2017-2021 @polkadot/rpc-augment authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@polkadot/rpc-augment', version: '7.1.2-5' };
