// Auto-generated via `yarn polkadot-types-from-defs`, do not edit
/* eslint-disable */

// import type lookup before we augment - in some environments
// this is required to allow for ambient/previous definitions
import '@polkadot/types/types/registry';

import type { AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff, AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake, AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation, AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation, AssetHubKusamaRuntimeDynamicParamsIssuanceParameters, AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey, AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue, AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight, AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight, AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters, AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey, AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue, AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock, AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight, AssetHubKusamaRuntimeDynamicParamsSchedulerParameters, AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey, AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions, AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages, AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters, AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey, AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue, AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase, AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock, AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase, AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination, AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion, AssetHubKusamaRuntimeDynamicParamsTreasuryParameters, AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey, AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue, AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin, AssetHubKusamaRuntimeOriginCaller, AssetHubKusamaRuntimeProxyType, AssetHubKusamaRuntimeRuntime, AssetHubKusamaRuntimeRuntimeError, AssetHubKusamaRuntimeRuntimeFreezeReason, AssetHubKusamaRuntimeRuntimeHoldReason, AssetHubKusamaRuntimeRuntimeParameters, AssetHubKusamaRuntimeRuntimeParametersKey, AssetHubKusamaRuntimeRuntimeParametersValue, AssetHubKusamaRuntimeRuntimeTask, AssetHubKusamaRuntimeSessionKeys, AssetHubKusamaRuntimeStakingNposCompactSolution24, AssetHubKusamaRuntimeTreasuryBurnDestinationAccount, FrameSupportStorageFootprint, PalletRecoveryAttempt, PalletRecoveryBitfield, PalletRecoveryFriendGroup, PalletRecoveryHoldReason, PalletRecoveryIdentifiedConsideration, PalletRemoteProxyCall, PalletRemoteProxyError, PalletRemoteProxyRemoteProxyProof, SpConsensusAuraSr25519AppSr25519Public } from '@polkadot/types/lookup';

declare module '@polkadot/types/types/registry' {
  interface InterfaceTypes {
    AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff: AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff;
    AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake: AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake;
    AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation: AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation;
    AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation: AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParameters: AssetHubKusamaRuntimeDynamicParamsIssuanceParameters;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey: AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue: AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight: AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight: AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters: AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey: AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue: AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue;
    AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock: AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock;
    AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight: AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParameters: AssetHubKusamaRuntimeDynamicParamsSchedulerParameters;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey: AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue: AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages: AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters: AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey: AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue: AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase: AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock: AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase: AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase;
    AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination: AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination;
    AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion: AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParameters: AssetHubKusamaRuntimeDynamicParamsTreasuryParameters;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey: AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue: AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue;
    AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin: AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin;
    AssetHubKusamaRuntimeOriginCaller: AssetHubKusamaRuntimeOriginCaller;
    AssetHubKusamaRuntimeProxyType: AssetHubKusamaRuntimeProxyType;
    AssetHubKusamaRuntimeRuntime: AssetHubKusamaRuntimeRuntime;
    AssetHubKusamaRuntimeRuntimeError: AssetHubKusamaRuntimeRuntimeError;
    AssetHubKusamaRuntimeRuntimeFreezeReason: AssetHubKusamaRuntimeRuntimeFreezeReason;
    AssetHubKusamaRuntimeRuntimeHoldReason: AssetHubKusamaRuntimeRuntimeHoldReason;
    AssetHubKusamaRuntimeRuntimeParameters: AssetHubKusamaRuntimeRuntimeParameters;
    AssetHubKusamaRuntimeRuntimeParametersKey: AssetHubKusamaRuntimeRuntimeParametersKey;
    AssetHubKusamaRuntimeRuntimeParametersValue: AssetHubKusamaRuntimeRuntimeParametersValue;
    AssetHubKusamaRuntimeRuntimeTask: AssetHubKusamaRuntimeRuntimeTask;
    AssetHubKusamaRuntimeSessionKeys: AssetHubKusamaRuntimeSessionKeys;
    AssetHubKusamaRuntimeStakingNposCompactSolution24: AssetHubKusamaRuntimeStakingNposCompactSolution24;
    AssetHubKusamaRuntimeTreasuryBurnDestinationAccount: AssetHubKusamaRuntimeTreasuryBurnDestinationAccount;
    FrameSupportStorageFootprint: FrameSupportStorageFootprint;
    PalletRecoveryAttempt: PalletRecoveryAttempt;
    PalletRecoveryBitfield: PalletRecoveryBitfield;
    PalletRecoveryFriendGroup: PalletRecoveryFriendGroup;
    PalletRecoveryHoldReason: PalletRecoveryHoldReason;
    PalletRecoveryIdentifiedConsideration: PalletRecoveryIdentifiedConsideration;
    PalletRemoteProxyCall: PalletRemoteProxyCall;
    PalletRemoteProxyError: PalletRemoteProxyError;
    PalletRemoteProxyRemoteProxyProof: PalletRemoteProxyRemoteProxyProof;
    SpConsensusAuraSr25519AppSr25519Public: SpConsensusAuraSr25519AppSr25519Public;
  } // InterfaceTypes
} // declare module
