// Auto-generated via `yarn polkadot-types-from-defs`, do not edit
/* eslint-disable */

// import type lookup before we augment - in some environments
// this is required to allow for ambient/previous definitions
import '@polkadot/types/types/registry';

import type { AssetHubKusamaRuntimeAhMigrationRcPalletsOrigin, AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff, AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake, AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation, AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation, AssetHubKusamaRuntimeDynamicParamsIssuanceParameters, AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey, AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue, AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight, AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight, AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters, AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey, AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue, AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock, AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight, AssetHubKusamaRuntimeDynamicParamsSchedulerParameters, AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey, AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration, AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions, AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages, AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters, AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey, AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue, AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase, AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock, AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase, AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination, AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion, AssetHubKusamaRuntimeDynamicParamsTreasuryParameters, AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey, AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue, AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin, AssetHubKusamaRuntimeOriginCaller, AssetHubKusamaRuntimeProxyType, AssetHubKusamaRuntimeRuntime, AssetHubKusamaRuntimeRuntimeError, AssetHubKusamaRuntimeRuntimeFreezeReason, AssetHubKusamaRuntimeRuntimeHoldReason, AssetHubKusamaRuntimeRuntimeParameters, AssetHubKusamaRuntimeRuntimeParametersKey, AssetHubKusamaRuntimeRuntimeParametersValue, AssetHubKusamaRuntimeRuntimeTask, AssetHubKusamaRuntimeSessionKeys, AssetHubKusamaRuntimeStakingNposCompactSolution24, AssetHubKusamaRuntimeTreasuryBurnDestinationAccount, PalletProxyProxyDefinitionAssetHubKusamaRuntimeProxyType, PalletProxyProxyDefinitionKusamaRuntimeConstantsProxyProxyType, PalletRcMigratorRecoveryPortableActiveRecovery, PalletRcMigratorRecoveryPortableRecoveryConfig, PalletRcMigratorRecoveryPortableRecoveryFriends, PalletRcMigratorRecoveryPortableRecoveryMessage, PalletRcMigratorSocietyPortableBid, PalletRcMigratorSocietyPortableBidKind, PalletRcMigratorSocietyPortableCandidacy, PalletRcMigratorSocietyPortableGroupParams, PalletRcMigratorSocietyPortableIntakeRecord, PalletRcMigratorSocietyPortableMemberRecord, PalletRcMigratorSocietyPortablePayoutRecord, PalletRcMigratorSocietyPortableSocietyMessage, PalletRcMigratorSocietyPortableTally, PalletRcMigratorSocietyPortableVote, PalletRcMigratorSocietyPortableVouchingStatus, PalletRcMigratorSocietySocietyValues, PalletRemoteProxyCall, PalletRemoteProxyError, PalletRemoteProxyRemoteProxyProof, PalletReviveEvmApiDebugRpcTypesPrestateTrace, PalletReviveEvmApiDebugRpcTypesPrestateTraceInfo, PalletReviveEvmApiDebugRpcTypesPrestateTracerConfig, PalletReviveStorageAccountInfo, PalletReviveStorageAccountType, PalletReviveVmCodeInfo, SpConsensusAuraSr25519AppSr25519Public } from '@polkadot/types/lookup';

declare module '@polkadot/types/types/registry' {
  interface InterfaceTypes {
    AssetHubKusamaRuntimeAhMigrationRcPalletsOrigin: AssetHubKusamaRuntimeAhMigrationRcPalletsOrigin;
    AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff: AssetHubKusamaRuntimeDynamicParamsIssuanceFalloff;
    AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake: AssetHubKusamaRuntimeDynamicParamsIssuanceIdealStake;
    AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation: AssetHubKusamaRuntimeDynamicParamsIssuanceMaxInflation;
    AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation: AssetHubKusamaRuntimeDynamicParamsIssuanceMinInflation;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParameters: AssetHubKusamaRuntimeDynamicParamsIssuanceParameters;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey: AssetHubKusamaRuntimeDynamicParamsIssuanceParametersKey;
    AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue: AssetHubKusamaRuntimeDynamicParamsIssuanceParametersValue;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight: AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnIdleWeight;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight: AssetHubKusamaRuntimeDynamicParamsMessageQueueMaxOnInitWeight;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters: AssetHubKusamaRuntimeDynamicParamsMessageQueueParameters;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey: AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersKey;
    AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue: AssetHubKusamaRuntimeDynamicParamsMessageQueueParametersValue;
    AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock: AssetHubKusamaRuntimeDynamicParamsSchedulerMaxScheduledPerBlock;
    AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight: AssetHubKusamaRuntimeDynamicParamsSchedulerMaximumWeight;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParameters: AssetHubKusamaRuntimeDynamicParamsSchedulerParameters;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey: AssetHubKusamaRuntimeDynamicParamsSchedulerParametersKey;
    AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue: AssetHubKusamaRuntimeDynamicParamsSchedulerParametersValue;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxElectingVoters;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxEraDuration;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions: AssetHubKusamaRuntimeDynamicParamsStakingElectionMaxSignedSubmissions;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages: AssetHubKusamaRuntimeDynamicParamsStakingElectionMinerPages;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters: AssetHubKusamaRuntimeDynamicParamsStakingElectionParameters;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey: AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersKey;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue: AssetHubKusamaRuntimeDynamicParamsStakingElectionParametersValue;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase: AssetHubKusamaRuntimeDynamicParamsStakingElectionSignedPhase;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock: AssetHubKusamaRuntimeDynamicParamsStakingElectionTargetSnapshotPerBlock;
    AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase: AssetHubKusamaRuntimeDynamicParamsStakingElectionUnsignedPhase;
    AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination: AssetHubKusamaRuntimeDynamicParamsTreasuryBurnDestination;
    AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion: AssetHubKusamaRuntimeDynamicParamsTreasuryBurnPortion;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParameters: AssetHubKusamaRuntimeDynamicParamsTreasuryParameters;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey: AssetHubKusamaRuntimeDynamicParamsTreasuryParametersKey;
    AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue: AssetHubKusamaRuntimeDynamicParamsTreasuryParametersValue;
    AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin: AssetHubKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin;
    AssetHubKusamaRuntimeOriginCaller: AssetHubKusamaRuntimeOriginCaller;
    AssetHubKusamaRuntimeProxyType: AssetHubKusamaRuntimeProxyType;
    AssetHubKusamaRuntimeRuntime: AssetHubKusamaRuntimeRuntime;
    AssetHubKusamaRuntimeRuntimeError: AssetHubKusamaRuntimeRuntimeError;
    AssetHubKusamaRuntimeRuntimeFreezeReason: AssetHubKusamaRuntimeRuntimeFreezeReason;
    AssetHubKusamaRuntimeRuntimeHoldReason: AssetHubKusamaRuntimeRuntimeHoldReason;
    AssetHubKusamaRuntimeRuntimeParameters: AssetHubKusamaRuntimeRuntimeParameters;
    AssetHubKusamaRuntimeRuntimeParametersKey: AssetHubKusamaRuntimeRuntimeParametersKey;
    AssetHubKusamaRuntimeRuntimeParametersValue: AssetHubKusamaRuntimeRuntimeParametersValue;
    AssetHubKusamaRuntimeRuntimeTask: AssetHubKusamaRuntimeRuntimeTask;
    AssetHubKusamaRuntimeSessionKeys: AssetHubKusamaRuntimeSessionKeys;
    AssetHubKusamaRuntimeStakingNposCompactSolution24: AssetHubKusamaRuntimeStakingNposCompactSolution24;
    AssetHubKusamaRuntimeTreasuryBurnDestinationAccount: AssetHubKusamaRuntimeTreasuryBurnDestinationAccount;
    PalletProxyProxyDefinitionAssetHubKusamaRuntimeProxyType: PalletProxyProxyDefinitionAssetHubKusamaRuntimeProxyType;
    PalletProxyProxyDefinitionKusamaRuntimeConstantsProxyProxyType: PalletProxyProxyDefinitionKusamaRuntimeConstantsProxyProxyType;
    PalletRcMigratorRecoveryPortableActiveRecovery: PalletRcMigratorRecoveryPortableActiveRecovery;
    PalletRcMigratorRecoveryPortableRecoveryConfig: PalletRcMigratorRecoveryPortableRecoveryConfig;
    PalletRcMigratorRecoveryPortableRecoveryFriends: PalletRcMigratorRecoveryPortableRecoveryFriends;
    PalletRcMigratorRecoveryPortableRecoveryMessage: PalletRcMigratorRecoveryPortableRecoveryMessage;
    PalletRcMigratorSocietyPortableBid: PalletRcMigratorSocietyPortableBid;
    PalletRcMigratorSocietyPortableBidKind: PalletRcMigratorSocietyPortableBidKind;
    PalletRcMigratorSocietyPortableCandidacy: PalletRcMigratorSocietyPortableCandidacy;
    PalletRcMigratorSocietyPortableGroupParams: PalletRcMigratorSocietyPortableGroupParams;
    PalletRcMigratorSocietyPortableIntakeRecord: PalletRcMigratorSocietyPortableIntakeRecord;
    PalletRcMigratorSocietyPortableMemberRecord: PalletRcMigratorSocietyPortableMemberRecord;
    PalletRcMigratorSocietyPortablePayoutRecord: PalletRcMigratorSocietyPortablePayoutRecord;
    PalletRcMigratorSocietyPortableSocietyMessage: PalletRcMigratorSocietyPortableSocietyMessage;
    PalletRcMigratorSocietyPortableTally: PalletRcMigratorSocietyPortableTally;
    PalletRcMigratorSocietyPortableVote: PalletRcMigratorSocietyPortableVote;
    PalletRcMigratorSocietyPortableVouchingStatus: PalletRcMigratorSocietyPortableVouchingStatus;
    PalletRcMigratorSocietySocietyValues: PalletRcMigratorSocietySocietyValues;
    PalletRemoteProxyCall: PalletRemoteProxyCall;
    PalletRemoteProxyError: PalletRemoteProxyError;
    PalletRemoteProxyRemoteProxyProof: PalletRemoteProxyRemoteProxyProof;
    PalletReviveEvmApiDebugRpcTypesPrestateTrace: PalletReviveEvmApiDebugRpcTypesPrestateTrace;
    PalletReviveEvmApiDebugRpcTypesPrestateTraceInfo: PalletReviveEvmApiDebugRpcTypesPrestateTraceInfo;
    PalletReviveEvmApiDebugRpcTypesPrestateTracerConfig: PalletReviveEvmApiDebugRpcTypesPrestateTracerConfig;
    PalletReviveStorageAccountInfo: PalletReviveStorageAccountInfo;
    PalletReviveStorageAccountType: PalletReviveStorageAccountType;
    PalletReviveVmCodeInfo: PalletReviveVmCodeInfo;
    SpConsensusAuraSr25519AppSr25519Public: SpConsensusAuraSr25519AppSr25519Public;
  } // InterfaceTypes
} // declare module
