// Auto-generated via `yarn polkadot-types-from-defs`, do not edit
/* eslint-disable */

// import type lookup before we augment - in some environments
// this is required to allow for ambient/previous definitions
import '@polkadot/types/types/registry';

import type { FrameSupportTokensMiscIdAmount, PolkadotPrimitivesV7ApprovalVotingParams, PolkadotPrimitivesV7AssignmentAppPublic, PolkadotPrimitivesV7AsyncBackingAsyncBackingParams, PolkadotPrimitivesV7AsyncBackingBackingState, PolkadotPrimitivesV7AsyncBackingCandidatePendingAvailability, PolkadotPrimitivesV7AsyncBackingConstraints, PolkadotPrimitivesV7AsyncBackingInboundHrmpLimitations, PolkadotPrimitivesV7AsyncBackingOutboundHrmpChannelLimitations, PolkadotPrimitivesV7BackedCandidate, PolkadotPrimitivesV7CandidateCommitments, PolkadotPrimitivesV7CandidateDescriptor, PolkadotPrimitivesV7CandidateEvent, PolkadotPrimitivesV7CandidateReceipt, PolkadotPrimitivesV7CollatorAppPublic, PolkadotPrimitivesV7CollatorAppSignature, PolkadotPrimitivesV7CommittedCandidateReceipt, PolkadotPrimitivesV7CoreState, PolkadotPrimitivesV7DisputeState, PolkadotPrimitivesV7DisputeStatement, PolkadotPrimitivesV7DisputeStatementSet, PolkadotPrimitivesV7ExecutorParams, PolkadotPrimitivesV7ExecutorParamsExecutorParam, PolkadotPrimitivesV7GroupRotationInfo, PolkadotPrimitivesV7IndexedVecGroupIndex, PolkadotPrimitivesV7IndexedVecValidatorIndex, PolkadotPrimitivesV7InherentData, PolkadotPrimitivesV7InvalidDisputeStatementKind, PolkadotPrimitivesV7OccupiedCore, PolkadotPrimitivesV7OccupiedCoreAssumption, PolkadotPrimitivesV7PersistedValidationData, PolkadotPrimitivesV7PvfCheckStatement, PolkadotPrimitivesV7PvfExecKind, PolkadotPrimitivesV7PvfPrepKind, PolkadotPrimitivesV7ScheduledCore, PolkadotPrimitivesV7ScrapedOnChainVotes, PolkadotPrimitivesV7SessionInfo, PolkadotPrimitivesV7SignedUncheckedSigned, PolkadotPrimitivesV7SlashingDisputeProof, PolkadotPrimitivesV7SlashingDisputesTimeSlot, PolkadotPrimitivesV7SlashingPendingSlashes, PolkadotPrimitivesV7SlashingSlashingOffenceKind, PolkadotPrimitivesV7UpgradeGoAhead, PolkadotPrimitivesV7UpgradeRestriction, PolkadotPrimitivesV7ValidDisputeStatementKind, PolkadotPrimitivesV7ValidatorAppPublic, PolkadotPrimitivesV7ValidatorAppSignature, PolkadotPrimitivesV7ValidityAttestation, PolkadotPrimitivesVstagingSchedulerParams, PolkadotRuntimeParachainsAssignerOnDemandPalletCall, PolkadotRuntimeParachainsAssignerOnDemandPalletError, PolkadotRuntimeParachainsAssignerOnDemandPalletEvent, PolkadotRuntimeParachainsAssignerOnDemandTypesCoreAffinityCount, PolkadotRuntimeParachainsAssignerOnDemandTypesEnqueuedOrder, PolkadotRuntimeParachainsAssignerOnDemandTypesQueueStatusType, StagingKusamaRuntimeDynamicParamsInflationFalloff, StagingKusamaRuntimeDynamicParamsInflationIdealStake, StagingKusamaRuntimeDynamicParamsInflationMaxInflation, StagingKusamaRuntimeDynamicParamsInflationMinInflation, StagingKusamaRuntimeDynamicParamsInflationParameters, StagingKusamaRuntimeDynamicParamsInflationParametersKey, StagingKusamaRuntimeDynamicParamsInflationParametersValue, StagingKusamaRuntimeDynamicParamsInflationUseAuctionSlots, StagingKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin, StagingKusamaRuntimeNposCompactSolution24, StagingKusamaRuntimeOriginCaller, StagingKusamaRuntimeProxyType, StagingKusamaRuntimeRuntime, StagingKusamaRuntimeRuntimeError, StagingKusamaRuntimeRuntimeFreezeReason, StagingKusamaRuntimeRuntimeHoldReason, StagingKusamaRuntimeRuntimeParameters, StagingKusamaRuntimeRuntimeParametersKey, StagingKusamaRuntimeRuntimeParametersValue, StagingKusamaRuntimeSessionKeys } from '@polkadot/types/lookup';

declare module '@polkadot/types/types/registry' {
  interface InterfaceTypes {
    FrameSupportTokensMiscIdAmount: FrameSupportTokensMiscIdAmount;
    PolkadotPrimitivesV7ApprovalVotingParams: PolkadotPrimitivesV7ApprovalVotingParams;
    PolkadotPrimitivesV7AssignmentAppPublic: PolkadotPrimitivesV7AssignmentAppPublic;
    PolkadotPrimitivesV7AsyncBackingAsyncBackingParams: PolkadotPrimitivesV7AsyncBackingAsyncBackingParams;
    PolkadotPrimitivesV7AsyncBackingBackingState: PolkadotPrimitivesV7AsyncBackingBackingState;
    PolkadotPrimitivesV7AsyncBackingCandidatePendingAvailability: PolkadotPrimitivesV7AsyncBackingCandidatePendingAvailability;
    PolkadotPrimitivesV7AsyncBackingConstraints: PolkadotPrimitivesV7AsyncBackingConstraints;
    PolkadotPrimitivesV7AsyncBackingInboundHrmpLimitations: PolkadotPrimitivesV7AsyncBackingInboundHrmpLimitations;
    PolkadotPrimitivesV7AsyncBackingOutboundHrmpChannelLimitations: PolkadotPrimitivesV7AsyncBackingOutboundHrmpChannelLimitations;
    PolkadotPrimitivesV7BackedCandidate: PolkadotPrimitivesV7BackedCandidate;
    PolkadotPrimitivesV7CandidateCommitments: PolkadotPrimitivesV7CandidateCommitments;
    PolkadotPrimitivesV7CandidateDescriptor: PolkadotPrimitivesV7CandidateDescriptor;
    PolkadotPrimitivesV7CandidateEvent: PolkadotPrimitivesV7CandidateEvent;
    PolkadotPrimitivesV7CandidateReceipt: PolkadotPrimitivesV7CandidateReceipt;
    PolkadotPrimitivesV7CollatorAppPublic: PolkadotPrimitivesV7CollatorAppPublic;
    PolkadotPrimitivesV7CollatorAppSignature: PolkadotPrimitivesV7CollatorAppSignature;
    PolkadotPrimitivesV7CommittedCandidateReceipt: PolkadotPrimitivesV7CommittedCandidateReceipt;
    PolkadotPrimitivesV7CoreState: PolkadotPrimitivesV7CoreState;
    PolkadotPrimitivesV7DisputeState: PolkadotPrimitivesV7DisputeState;
    PolkadotPrimitivesV7DisputeStatement: PolkadotPrimitivesV7DisputeStatement;
    PolkadotPrimitivesV7DisputeStatementSet: PolkadotPrimitivesV7DisputeStatementSet;
    PolkadotPrimitivesV7ExecutorParams: PolkadotPrimitivesV7ExecutorParams;
    PolkadotPrimitivesV7ExecutorParamsExecutorParam: PolkadotPrimitivesV7ExecutorParamsExecutorParam;
    PolkadotPrimitivesV7GroupRotationInfo: PolkadotPrimitivesV7GroupRotationInfo;
    PolkadotPrimitivesV7IndexedVecGroupIndex: PolkadotPrimitivesV7IndexedVecGroupIndex;
    PolkadotPrimitivesV7IndexedVecValidatorIndex: PolkadotPrimitivesV7IndexedVecValidatorIndex;
    PolkadotPrimitivesV7InherentData: PolkadotPrimitivesV7InherentData;
    PolkadotPrimitivesV7InvalidDisputeStatementKind: PolkadotPrimitivesV7InvalidDisputeStatementKind;
    PolkadotPrimitivesV7OccupiedCore: PolkadotPrimitivesV7OccupiedCore;
    PolkadotPrimitivesV7OccupiedCoreAssumption: PolkadotPrimitivesV7OccupiedCoreAssumption;
    PolkadotPrimitivesV7PersistedValidationData: PolkadotPrimitivesV7PersistedValidationData;
    PolkadotPrimitivesV7PvfCheckStatement: PolkadotPrimitivesV7PvfCheckStatement;
    PolkadotPrimitivesV7PvfExecKind: PolkadotPrimitivesV7PvfExecKind;
    PolkadotPrimitivesV7PvfPrepKind: PolkadotPrimitivesV7PvfPrepKind;
    PolkadotPrimitivesV7ScheduledCore: PolkadotPrimitivesV7ScheduledCore;
    PolkadotPrimitivesV7ScrapedOnChainVotes: PolkadotPrimitivesV7ScrapedOnChainVotes;
    PolkadotPrimitivesV7SessionInfo: PolkadotPrimitivesV7SessionInfo;
    PolkadotPrimitivesV7SignedUncheckedSigned: PolkadotPrimitivesV7SignedUncheckedSigned;
    PolkadotPrimitivesV7SlashingDisputeProof: PolkadotPrimitivesV7SlashingDisputeProof;
    PolkadotPrimitivesV7SlashingDisputesTimeSlot: PolkadotPrimitivesV7SlashingDisputesTimeSlot;
    PolkadotPrimitivesV7SlashingPendingSlashes: PolkadotPrimitivesV7SlashingPendingSlashes;
    PolkadotPrimitivesV7SlashingSlashingOffenceKind: PolkadotPrimitivesV7SlashingSlashingOffenceKind;
    PolkadotPrimitivesV7UpgradeGoAhead: PolkadotPrimitivesV7UpgradeGoAhead;
    PolkadotPrimitivesV7UpgradeRestriction: PolkadotPrimitivesV7UpgradeRestriction;
    PolkadotPrimitivesV7ValidDisputeStatementKind: PolkadotPrimitivesV7ValidDisputeStatementKind;
    PolkadotPrimitivesV7ValidatorAppPublic: PolkadotPrimitivesV7ValidatorAppPublic;
    PolkadotPrimitivesV7ValidatorAppSignature: PolkadotPrimitivesV7ValidatorAppSignature;
    PolkadotPrimitivesV7ValidityAttestation: PolkadotPrimitivesV7ValidityAttestation;
    PolkadotPrimitivesVstagingSchedulerParams: PolkadotPrimitivesVstagingSchedulerParams;
    PolkadotRuntimeParachainsAssignerOnDemandPalletCall: PolkadotRuntimeParachainsAssignerOnDemandPalletCall;
    PolkadotRuntimeParachainsAssignerOnDemandPalletError: PolkadotRuntimeParachainsAssignerOnDemandPalletError;
    PolkadotRuntimeParachainsAssignerOnDemandPalletEvent: PolkadotRuntimeParachainsAssignerOnDemandPalletEvent;
    PolkadotRuntimeParachainsAssignerOnDemandTypesCoreAffinityCount: PolkadotRuntimeParachainsAssignerOnDemandTypesCoreAffinityCount;
    PolkadotRuntimeParachainsAssignerOnDemandTypesEnqueuedOrder: PolkadotRuntimeParachainsAssignerOnDemandTypesEnqueuedOrder;
    PolkadotRuntimeParachainsAssignerOnDemandTypesQueueStatusType: PolkadotRuntimeParachainsAssignerOnDemandTypesQueueStatusType;
    StagingKusamaRuntimeDynamicParamsInflationFalloff: StagingKusamaRuntimeDynamicParamsInflationFalloff;
    StagingKusamaRuntimeDynamicParamsInflationIdealStake: StagingKusamaRuntimeDynamicParamsInflationIdealStake;
    StagingKusamaRuntimeDynamicParamsInflationMaxInflation: StagingKusamaRuntimeDynamicParamsInflationMaxInflation;
    StagingKusamaRuntimeDynamicParamsInflationMinInflation: StagingKusamaRuntimeDynamicParamsInflationMinInflation;
    StagingKusamaRuntimeDynamicParamsInflationParameters: StagingKusamaRuntimeDynamicParamsInflationParameters;
    StagingKusamaRuntimeDynamicParamsInflationParametersKey: StagingKusamaRuntimeDynamicParamsInflationParametersKey;
    StagingKusamaRuntimeDynamicParamsInflationParametersValue: StagingKusamaRuntimeDynamicParamsInflationParametersValue;
    StagingKusamaRuntimeDynamicParamsInflationUseAuctionSlots: StagingKusamaRuntimeDynamicParamsInflationUseAuctionSlots;
    StagingKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin: StagingKusamaRuntimeGovernanceOriginsPalletCustomOriginsOrigin;
    StagingKusamaRuntimeNposCompactSolution24: StagingKusamaRuntimeNposCompactSolution24;
    StagingKusamaRuntimeOriginCaller: StagingKusamaRuntimeOriginCaller;
    StagingKusamaRuntimeProxyType: StagingKusamaRuntimeProxyType;
    StagingKusamaRuntimeRuntime: StagingKusamaRuntimeRuntime;
    StagingKusamaRuntimeRuntimeError: StagingKusamaRuntimeRuntimeError;
    StagingKusamaRuntimeRuntimeFreezeReason: StagingKusamaRuntimeRuntimeFreezeReason;
    StagingKusamaRuntimeRuntimeHoldReason: StagingKusamaRuntimeRuntimeHoldReason;
    StagingKusamaRuntimeRuntimeParameters: StagingKusamaRuntimeRuntimeParameters;
    StagingKusamaRuntimeRuntimeParametersKey: StagingKusamaRuntimeRuntimeParametersKey;
    StagingKusamaRuntimeRuntimeParametersValue: StagingKusamaRuntimeRuntimeParametersValue;
    StagingKusamaRuntimeSessionKeys: StagingKusamaRuntimeSessionKeys;
  } // InterfaceTypes
} // declare module
