// Copyright 2017-2022 @polkadot/types-create authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/types-create', path: 'auto', type: 'auto', version: '7.8.2-1' };
