// Copyright 2017-2019 @polkadot/api authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

import { KeyringPair } from '@polkadot/keyring/types';

import fs from 'fs';
import path from 'path';

import { Abi } from '@polkadot/api-contract';
import testingPairs from '@polkadot/keyring/testingPairs';
import { Address, Hash, RuntimeVersion } from '@polkadot/types';

import { ApiPromise, SubmittableResult } from '../../src';

// Backwards compatibility:
// A breaking change was introduced by substrate runtime spec version 97. https://github.com/paritytech/substrate/pull/2911/files
// The change had to be implemented in ink! which changed the structure of the Wasm files.
// That's why we need two different versions of the generated contract files.
// If the substrate version is older than this https://github.com/paritytech/substrate/pull/2911 it will only work
// with contracts generated by an ink! version prior to https://github.com/paritytech/ink/pull/129 and vice versa.
import incrementerAbiPre97 from '../../../api-contract/test/contracts-20190529_b6ab9b3/Incrementer.json';
import incrementerAbiPost97 from '../../../api-contract/test/contracts-20190625_9589899/Incrementer.json';

const incrementerCodePre97 = fs.readFileSync(path.join(__dirname, '../../../api-contract/test/contracts-20190529_b6ab9b3/incrementer-pruned.wasm')).toString('hex');
const incrementerCodePost97 = fs.readFileSync(path.join(__dirname, '../../../api-contract/test/contracts-20190625_9589899/incrementer-pruned.wasm')).toString('hex');

describe('Promise e2e contracts', () => {
  let address: Address;
  let api: ApiPromise;
  let codeHash: Hash;
  let keyring: {
    [index: string]: KeyringPair
  };
  let txBase: any;
  let section: string;
  let runtimeVersion: RuntimeVersion;

  beforeEach(async (done) => {
    if (!api) {
      api = await ApiPromise.create();
    }

    // Backwards compatibility:
    // srml-contract has been renamed to srml-contracts with runtime spec_version 96 https://github.com/paritytech/substrate/pull/2905
    txBase = api.tx.contracts || api.tx.contract;
    section = api.tx.contracts ? 'contracts' : 'contract';
    keyring = testingPairs({ type: 'sr25519' });
    runtimeVersion = await api.runtimeVersion;

    jest.setTimeout(10000);
    done();
  });

  describe('incrementer', () => {
    const MAX_GAS = 500000;
    let abi: Abi;

    beforeEach(() => {
      abi = runtimeVersion.specVersion.toNumber() < 97
        ? new Abi(incrementerAbiPre97)
        : new Abi(incrementerAbiPost97);
    });

    it('allows putCode', (done) => {
      const incrementerCode = runtimeVersion.specVersion.toNumber() < 97
      ? incrementerCodePre97
      : incrementerCodePost97;

      return (
        txBase
          .putCode(MAX_GAS, `0x${incrementerCode}`)
          .signAndSend(keyring.alice, (result: SubmittableResult) => {
            if (result.status.isFinalized) {
              const record = result.findRecord(section, 'CodeStored');
              if (record) {
                codeHash = record.event.data[0] as Hash;

                done();
              }
            }
          })
      );
    });

    it('allows contract create', (done) => {
      expect(codeHash).toBeDefined();

      // An instance of a contract can only be deployed once by one specific account.
      // That'S why we need a random starting point for out incrementer contract to be
      // able to run this test multiple times without the need of pruning the database
      const randomStart = Math.floor(Math.random() * (1000000));

      return (
        txBase
          .create(12345, MAX_GAS, codeHash, abi.deploy(randomStart))
          .signAndSend(keyring.bob, (result: SubmittableResult) => {
            console.error('create', JSON.stringify(result));

            if (result.status.isFinalized) {
              const record = result.findRecord(section, 'Instantiated');

              if (record) {
                address = record.event.data[1] as Address;

                done();
              }
            }
          })
      );
    });

    it('allows contract call', (done) => {
      expect(address).toBeDefined();

      return (
        txBase
          .call(address, 12345, MAX_GAS, abi.messages.inc(3))
          .signAndSend(keyring.bob, (result: SubmittableResult) => {
            console.error('call', JSON.stringify(result));

            if (result.status.isFinalized && result.findRecord('system', 'ExtrinsicSuccess')) {
              done();
            }
          })
      );
    });
  });
});
