// Copyright 2017-2019 @polkadot/types authors & contributors
// This software may be modified and distributed under the terms
// of the Apache-2.0 license. See the LICENSE file for details.

import U32 from './U32';

/**
 * @name USize
 * @description
 * A System default unsigned number, typically used in RPC to report non-consensus
 * data. It is a wrapper for [[U32]] as a WASM default (as generated by Rust bindings)
 */
export default class USize extends U32 {
  /**
   * @description Returns the base runtime type name for this instance
   */
  toRawType (): string {
    return 'usize';
  }
}
