name: PR
on: [pull_request]

jobs:
  pr:
    continue-on-error: true
    strategy:
      matrix:
        step: ['lint', 'test', 'build', 'deno']
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        # This will default to using v20 so that CI will pass.
        # ref: https://github.com/polkadot-js/api/issues/6017
        node-version: 'lts/iron'
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.42.x
    - name: ${{ matrix.step }}
      if: always()
      run: |
        yarn install --immutable
        yarn ${{ matrix.step }}
